from pathlib import Path

p = Path('ui.js')
s = p.read_text(encoding='utf-8')
old = '''async function restoreFile(event){\n  var file=event.target.files&&event.target.files[0];event.target.value="";if(!file)return;\n  try{\n    var backup=JSON.parse(await file.text());\n    if(backup.format!=="rsm-crm-backup"||!backup.data)throw new Error("Bu dosya geçerli bir RSM CRM yedeği değil.");\n    if(!confirm("Mevcut CRM kayıtları yedekteki kayıtlarla değiştirilecek. Devam edilsin mi?"))return;\n    busy(true);await api("/restore",{method:"POST",body:JSON.stringify({confirm:"RSM CRM",data:backup.data})});closeModal();await load();toast("Yedek başarıyla geri yüklendi.");\n  }catch(error){toast(error.message,true)}finally{busy(false)}\n}'''
new = '''async function restoreFile(event){\n  var file=event.target.files&&event.target.files[0];event.target.value="";if(!file)return;\n  try{\n    var backup=JSON.parse(await file.text());\n    if(backup.format!=="rsm-crm-backup"||!backup.data)throw new Error("Bu dosya geçerli bir RSM CRM yedeği değil.");\n    var data=backup.data;\n    var emsalOnly=data.emsal_only===true&&Array.isArray(data.emsal);\n    if(emsalOnly){\n      if(!confirm("Bu dosya Emsal Havuzu aktarımıdır. CRM müşterileri, talepleri ve portföyleri silinmez. Emsal kayıtları parça parça aktarılacak. Devam edilsin mi?"))return;\n      busy(true);\n      var total=data.emsal.length;\n      var history=data.emsal_price_history||[];\n      var chunkSize=50;\n      var done=0;\n      for(var i=0;i<total;i+=chunkSize){\n        var payload={emsal_only:true,customers:[],owners:[],properties:[],demands:[],tasks:[],emsal:data.emsal.slice(i,i+chunkSize),emsal_price_history:history.slice(Math.floor(i*history.length/total),Math.floor((i+chunkSize)*history.length/total))};\n        await api("/restore",{method:"POST",body:JSON.stringify({confirm:"RSM CRM",data:payload})});\n        done=Math.min(i+chunkSize,total);\n        el("modalBody").querySelector(".restore-progress")?.replaceChildren(document.createTextNode("Emsal aktarılıyor: "+done+" / "+total));\n      }\n      closeModal();await load();await loadEmsal();toast(total+" Emsal kaydı CRM Emsal Havuzu'na aktarıldı.");\n      return;\n    }\n    if(!confirm("Mevcut CRM kayıtları yedekteki kayıtlarla değiştirilecek. Devam edilsin mi?"))return;\n    busy(true);await api("/restore",{method:"POST",body:JSON.stringify({confirm:"RSM CRM",data:data})});closeModal();await load();toast("Yedek başarıyla geri yüklendi.");\n  }catch(error){toast(error.message,true)}finally{busy(false)}\n}'''
if old not in s:
    raise SystemExit('restoreFile pattern not found')
s=s.replace(old,new)
s=s.replace('var total=data.emsal.length;\n      var history=data.emsal_price_history||[];', 'var total=data.emsal.length;\n      var history=data.emsal_price_history||[];\n      el("modalBody").insertAdjacentHTML("afterbegin","<p class=\\"restore-progress muted\\">Emsal aktarımı hazırlanıyor…</p>");')
p.write_text(s,encoding='utf-8')
print('patched chunked Emsal restore')
